<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TurnOffCommand" Id="{7bc8b26d-52a2-4d18-b9a0-dfa25e1824f4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TurnOffCommand EXTENDS I_Command
VAR
	_device	:I_Device;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="execute" Id="{fb8e3201-89ad-48ff-989e-cad5f6c0930d}">
      <Declaration><![CDATA[METHOD execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_device.turnOff();]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{a96e9b2b-2a90-446a-8ed0-3f6fb34f6ce1}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	
	device	:I_Device;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^._device := device;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="TurnOffCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="TurnOffCommand.execute">
      <LineId Id="3" Count="0" />
    </LineIds>
    <LineIds Name="TurnOffCommand.FB_init">
      <LineId Id="7" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>